<attachment id="file:kivy-instagram-ui/kivy-instagram-ui/src/kv/main.kv">
BoxLayout:
    orientation: 'vertical'

    NavBar:
        id: nav_bar

    ScreenManager:
        id: screen_manager

        HomeScreen:
            name: 'home'

        ProfileScreen:
            name: 'profile'

        ExploreScreen:
            name: 'explore'

        PostDetailScreen:
            name: 'post_detail'
</attachment>